#!/usr/bin/env node
// Regenerates the STICKER_ART data block inside templates.js from registry.json
// and vendor/*.svg. The generator scripts run inside a sandbox with no filesystem
// and no module loader, so templates.js must carry the vendored artwork verbatim
// as source text — this script is how that inlining happens, and it is meant to
// be re-run (and re-committed) whenever registry.json or vendor/ changes.
//
// Usage: node gallery-samples/21-sticker-press/build-artwork.mjs
//
// Deterministic: same registry.json + vendor/ content in, byte-identical
// templates.js STICKER_ART block out. Only the text strictly between the two
// marker comments below is replaced — everything else in templates.js is left
// untouched, so this can be re-run safely after the layout engine (or any later
// task's chrome code) has been added around it.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(fileURLToPath(import.meta.url));
const TEMPLATES_PATH = join(ROOT, 'templates.js');
const REGISTRY_PATH = join(ROOT, 'registry.json');

const START_MARKER = '// ---- STICKER ART START (generated by build-artwork.mjs — do not hand-edit) ----';
const END_MARKER = '// ---- STICKER ART END ----';

function loadRegistry() {
    const entries = JSON.parse(readFileSync(REGISTRY_PATH, 'utf8'));
    // Sort by id for a stable, diff-friendly, source-order-independent block —
    // registry.json's own entry order has drifted from category order across
    // several curation reworks (Task B's addenda), so id order is the one
    // ordering that stays deterministic regardless of future edits appending
    // rather than inserting.
    return [...entries].sort((a, b) => a.id.localeCompare(b.id));
}

function svgFor(entry) {
    const path = join(ROOT, 'vendor', entry.source, `${entry.id}.svg`);
    return readFileSync(path, 'utf8');
}

function buildDataBlock() {
    const entries = loadRegistry();
    const lines = entries.map(entry => {
        const svg = svgFor(entry);
        // Value shape: [name, cat, svg]. `source` ('lucide'|'twemoji') is not
        // stored — every id is prefixed with its source name (enforced by
        // stickerPressRegistry.test.ts and stickerPressVendor.test.ts), so
        // templates.js derives it from the id prefix instead of paying to
        // store it 500 times.
        const tuple = JSON.stringify([entry.name, entry.cat, svg]);
        return `${JSON.stringify(entry.id)}:${tuple}`;
    });
    return `const STICKER_ART = {\n${lines.join(',\n')}\n};`;
}

function spliceIntoTemplates(dataBlock) {
    const source = readFileSync(TEMPLATES_PATH, 'utf8');
    const startIdx = source.indexOf(START_MARKER);
    const endIdx = source.indexOf(END_MARKER);
    if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
        throw new Error(
            `templates.js is missing the STICKER ART markers. Expected both:\n  ${START_MARKER}\n  ${END_MARKER}`
        );
    }
    const before = source.slice(0, startIdx + START_MARKER.length);
    const after = source.slice(endIdx);
    const next = `${before}\n${dataBlock}\n${after}`;
    writeFileSync(TEMPLATES_PATH, next);
    return next;
}

function main() {
    const dataBlock = buildDataBlock();
    const next = spliceIntoTemplates(dataBlock);
    const bytes = Buffer.byteLength(next, 'utf8');
    console.log(`Inlined artwork for ${loadRegistry().length} stickers.`);
    console.log(`templates.js is now ${bytes} bytes (${(bytes / 1024).toFixed(1)} KiB).`);
}

if (import.meta.url === `file://${process.argv[1]}`) {
    main();
}

export { buildDataBlock, spliceIntoTemplates };
