import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

const REGISTRY_PATH = 'gallery-samples/21-sticker-press/registry.json';
const MANIFEST_PATH = 'gallery-samples/21-sticker-press/vendor/manifest.json';

type Source = 'lucide' | 'twemoji' | 'furniture';
interface Entry {
    id: string;
    name: string;
    cat: string;
    source: Source;
    upstream: string;
    keywords: string[];
}

const registry = (): Entry[] => JSON.parse(readFileSync(REGISTRY_PATH, 'utf8'));
const manifest = () => JSON.parse(readFileSync(MANIFEST_PATH, 'utf8'));

// The 18 categories and their curated counts. The spec's original per-category
// table sums to 480 (not 500) once the fixed 50/300/150 band split is honoured
// — Lucide alone is short 20 against its 300 target across the table's own
// numbers — and several individual counts shifted further once curation met
// what Lucide/Twemoji actually contain at acceptable size and quality (see
// taskB-report.md for the full account: byte-cap casualties, live-upstream
// 404s on deprecated npm aliases, and the botanical Twemoji shortfall). The
// 50/300/150 band split itself is exact and non-negotiable.
const EXPECTED_CATEGORY_COUNTS: Record<string, number> = {
    'index-tabs-flags': 18,
    'banners-ribbons': 16,
    'labels-tape': 16,
    'arrows-pointers': 36,
    'boxes-bullets-markers': 31,
    'stars-sparkles-awards': 27,
    'dividers-corners-frames': 25,
    'weather-sky': 26,
    botanical: 22,
    animals: 34,
    'food-drink': 35,
    'faces-moods': 24,
    'study-work': 43,
    'health-self-care': 29,
    'travel-places': 30,
    'celebration-seasons': 26,
    'money-home': 33,
    'symbols-misc': 29,
};

describe('sticker press registry', () => {
    it('has exactly 500 entries', () => {
        expect(registry()).toHaveLength(500);
    });

    it('splits into 50 furniture / 300 lucide / 150 twemoji', () => {
        const r = registry();
        expect(r.filter(e => e.source === 'furniture')).toHaveLength(50);
        expect(r.filter(e => e.source === 'lucide')).toHaveLength(300);
        expect(r.filter(e => e.source === 'twemoji')).toHaveLength(150);
    });

    it('covers exactly the 18 expected categories, with counts summing to 500 and matching membership', () => {
        const r = registry();
        const cats = Object.keys(EXPECTED_CATEGORY_COUNTS);
        expect(cats).toHaveLength(18);
        expect(Object.values(EXPECTED_CATEGORY_COUNTS).reduce((a, b) => a + b, 0)).toBe(500);

        const actualCats = new Set(r.map(e => e.cat));
        expect([...actualCats].sort()).toEqual([...cats].sort());

        cats.forEach(cat => {
            const actual = r.filter(e => e.cat === cat).length;
            expect(actual, `category ${cat}`).toBe(EXPECTED_CATEGORY_COUNTS[cat]);
        });
    });

    it('has unique ids and unique names', () => {
        const r = registry();
        expect(new Set(r.map(e => e.id)).size).toBe(r.length);
        expect(new Set(r.map(e => e.name)).size).toBe(r.length);
    });

    it('gives every non-furniture entry a manifest counterpart, and no orphans either way', () => {
        const r = registry();
        const m = manifest();
        const manifestIds = new Set(m.icons.map((i: any) => i.id));
        const nonFurniture = r.filter(e => e.source !== 'furniture');

        nonFurniture.forEach(e => {
            expect(manifestIds.has(e.id), `registry entry ${e.id} has no manifest counterpart`).toBe(true);
        });

        const registryIds = new Set(nonFurniture.map(e => e.id));
        m.icons.forEach((i: any) => {
            expect(registryIds.has(i.id), `manifest entry ${i.id} is not named by the registry`).toBe(true);
        });

        // Furniture is generated by templates.js's builders, never vendored.
        r.filter(e => e.source === 'furniture').forEach(e => {
            expect(manifestIds.has(e.id), `furniture entry ${e.id} should not be vendored`).toBe(false);
        });
    });

    it('gives every entry at least one keyword', () => {
        registry().forEach(e => {
            expect(Array.isArray(e.keywords), e.id).toBe(true);
            expect(e.keywords.length, `${e.id} keywords`).toBeGreaterThan(0);
            e.keywords.forEach(k => expect(typeof k, `${e.id} keyword`).toBe('string'));
        });
    });

    it('names every sticker for a human — no raw codepoints, no kebab-case leaking through', () => {
        const HEX_CODEPOINT = /^[0-9a-f]{4,7}$/i;
        const KEBAB_CASE = /^[a-z0-9]+(-[a-z0-9]+)+$/; // all-lowercase, hyphen-joined, no spaces
        registry().forEach(e => {
            expect(HEX_CODEPOINT.test(e.name), `${e.id} name "${e.name}" looks like a raw codepoint`).toBe(false);
            expect(KEBAB_CASE.test(e.name), `${e.id} name "${e.name}" looks like kebab-case`).toBe(false);
            // A human name has at least one letter and starts capitalised.
            expect(/[a-zA-Z]/.test(e.name), `${e.id} name "${e.name}" has no letters`).toBe(true);
            expect(e.name[0], `${e.id} name "${e.name}" should start capitalised`).toBe(e.name[0].toUpperCase());
        });
    });

    it('every entry’s id is prefixed by its source, except furniture', () => {
        registry().forEach(e => {
            if (e.source === 'furniture') {
                expect(e.id.startsWith('furn-'), e.id).toBe(true);
            } else {
                expect(e.id.startsWith(`${e.source}-`), e.id).toBe(true);
            }
        });
    });

    it('every furniture entry names a builder call, not a fetch path', () => {
        registry().filter(e => e.source === 'furniture').forEach(e => {
            expect(e.upstream, e.id).toMatch(/^[a-zA-Z]+\(.*\)$/);
        });
    });
});
